steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  secretEnv: ['FIREBASE_API_KEY']
  args:
    - -c
    - |
      echo "Firebase API Key is: $FIREBASE_API_KEY"

secrets:
- secretEnv:
    FIREBASE_API_KEY: projects/$PROJECT_ID/secrets/FIREBASE_API_KEY/versions/latest
